apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: hospital-frontend
  template:
    metadata:
      labels:
        app: hospital-frontend
    spec:
      containers:
        - name: hospital-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
