apiVersion: v1
kind: Service
metadata:
  name: hospital-frontend-service
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: hospital-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
