apiVersion: v1
kind: Secret
metadata:
  name: hospital-secret
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  POSTGRES_USER: "{{ .Values.postgres.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  DATABASE_URL: "{{ .Values.postgres.databaseUrl }}"
  JWT_SECRET: "{{ .Values.jwt.secret }}"
  JWT_REFRESH_SECRET: "{{ .Values.jwt.refreshSecret }}"
